"""add_user_typed_id_unique_constraint

Revision ID: 6ca7ef333ec7
Revises: 83527375f60a
Create Date: 2025-10-21 14:50:34.626402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca7ef333ec7'
down_revision = '83527375f60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_user_typed_id'))
        batch_op.create_index(batch_op.f('ix_patients_user_typed_id'), ['user_typed_id'], unique=False)
        batch_op.create_unique_constraint('uq_pulmo_typedid', ['pulmonologist_id', 'user_typed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pulmo_typedid', type_='unique')
        batch_op.drop_index(batch_op.f('ix_patients_user_typed_id'))
        batch_op.create_index(batch_op.f('ix_patients_user_typed_id'), ['user_typed_id'], unique=True)

    # ### end Alembic commands ###
