"""add_report

Revision ID: 83527375f60a
Revises: 
Create Date: 2025-10-21 11:22:18.698944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83527375f60a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pulmonologist_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('pulmonologist_report_s3_key', sa.String(length=1024), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_pulmonologist_id'), ['pulmonologist_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['pulmonologist_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_pulmonologist_id'))
        batch_op.drop_column('pulmonologist_report_s3_key')
        batch_op.drop_column('pulmonologist_id')

    # ### end Alembic commands ###
